// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmzgGl-6D3fWbFAgDIotfTp2O0FQW6yqI',
    appId: '1:523284382246:web:f9d22eec7589ad738c5ce7',
    messagingSenderId: '523284382246',
    projectId: 'tugas13-c75c3',
    authDomain: 'tugas13-c75c3.firebaseapp.com',
    storageBucket: 'tugas13-c75c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWD2Ol-nBLyhP9ULEiB8ElvsOpXiKeGw',
    appId: '1:523284382246:android:c482f726b394c5578c5ce7',
    messagingSenderId: '523284382246',
    projectId: 'tugas13-c75c3',
    storageBucket: 'tugas13-c75c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuO6-trb2Fs4ojj_B_WzEOkXuZPzUZ930',
    appId: '1:523284382246:ios:5bf5b10408a872238c5ce7',
    messagingSenderId: '523284382246',
    projectId: 'tugas13-c75c3',
    storageBucket: 'tugas13-c75c3.appspot.com',
    iosBundleId: 'com.example.sanberappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuO6-trb2Fs4ojj_B_WzEOkXuZPzUZ930',
    appId: '1:523284382246:ios:5216ae88a40f88708c5ce7',
    messagingSenderId: '523284382246',
    projectId: 'tugas13-c75c3',
    storageBucket: 'tugas13-c75c3.appspot.com',
    iosBundleId: 'com.example.sanberappflutter.RunnerTests',
  );
}
